version: '3'

services:
  redis:
    image: redis:6
  browse-scaler-cicd:
    image: browse-scaler:test-cicd
    build:
      context: ./
      dockerfile: Dockerfile.test
    volumes:
      - ./__test__:/app/artifacts
      - ./coverage:/app/coverage
    command: npm run ci-test
    environment:
      - JEST_JUNIT_OUTPUT=./artifacts/junit.xml
      - REDIS_URL=redis
      - CMR_ROOT=cmr.ci-test.earthdata.nasa.gov
      - CMR_ECHO_TOKEN=mock-ci-token
    depends_on:
      - redis
